name: Pets
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: me.petterim1.pets.Main
description: Pets plugin for Nukkit
website: https://github.com/PetteriM1/Pets/

commands:
  pet:
    description: Pets command
    usage: "/pet"
    permission: pets.manage

permissions:
  pets.manage:
    description: "Allows user to manage pets"
    default: op